// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuizApi.Services;

#nullable disable

namespace QuizApi.Migrations.ActivityLogDB
{
    [DbContext(typeof(ActivityLogDBContext))]
    partial class ActivityLogDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuizApi.Services.ErrorActivityLogModel", b =>
                {
                    b.Property<string>("ErrorActivityLogId")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("ErrorLevel")
                        .HasColumnType("text");

                    b.Property<string>("FromJsonObject")
                        .HasColumnType("text");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<string>("ToJsonObject")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UtcDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ErrorActivityLogId");

                    b.ToTable("ErrorLog");
                });

            modelBuilder.Entity("QuizApi.Services.UserActivityLogModel", b =>
                {
                    b.Property<string>("UserActivityLogId")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("ActionLevel")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FromJsonObject")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceKeyId")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceTable")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("ToJsonObject")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UtcDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserActivityLogId");

                    b.ToTable("UserActivityLog");
                });
#pragma warning restore 612, 618
        }
    }
}
